
modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory
license="MIT"
[[mods]] #mandatory
modId="notsoshrimple" #mandatory
version="1.1" #mandatory
displayName="Not So Shrimple" #mandatory
logoFile="examplemod.png" #optional
credits="Very special thanks to Alpha, Gec Master#7889 for the model and textures!" #optional
authors="Peeko32213" #optional
description='''
It's Kinda shrimple if you think about it
'''

[[dependencies.notsoshrimple]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.notsoshrimple]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.notsoshrimple]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.1.27,3.1.39]"
    ordering="BEFORE"
    side="BOTH"
